config/routes.rb
Rails.application.routes.draw do

  get '/auth/:provider/callback', to: 'travelers#create'

  post '/logout' => 'sessions#destroy'

  resources :sessions, only: [:new, :create, :destroy]
  resources :travelers, only: [:new, :create, :show]
  resources :trips
  resources :locations do
    resources :countries, only: [:new, :create, :destroy]
  end
  resources :countries

  get '/about' => 'welcome#about'

  root 'welcome#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord

    has_many :locations

end

app/models/location.rb
class Location < ApplicationRecord

    default_scope {order(:city)}

    belongs_to :country
    has_many :trips
    has_many :travelers, through: :trips

    def country_name
        self.try(:country).try(:name)
    end

    def country_name=(name)
        self.country = Country.find_or_create_by(name: name)
    end

    def name
        self.city + ', ' + self.country_name
    end

end

app/models/traveler.rb
class Traveler < ApplicationRecord

    has_secure_password

    validates :username, presence: true
    validates :username, uniqueness: true

    has_many :trips
    has_many :locations, through: :trips

    def trip_pluralizer
        trip_count = self.trips.count
        "#{trip_count} #{'trip'.pluralize(trip_count)}."
    end

    def trips_taken
        self.trips.collect { |trip| trip_taken?(trip.date) if !trip.date.nil? }.filter{ |date| date }.count
    end

    def trips_total
        if collect_trip_costs.all? { |cost| cost.nil? }
            '$0'
        else
            '$' + collect_trip_costs.filter { |cost| !cost.nil? }.reduce(:+).to_s
        end
    end

    private

    def collect_trip_costs
        self.trips.collect { |trip| trip.cost }
    end

    def date_today
        Time.zone.now.strftime('%m/%d/%Y')
    end

    def numberize(date)
        month, day, year = date.split('/')
        (year + month + day).to_i
    end

    def trip_taken?(trip_date)
        numberize(date_today) > numberize(trip_date)
    end

end

app/models/trip.rb
class Trip < ApplicationRecord

    belongs_to :traveler
    belongs_to :location

    validates :traveler_id, presence: true
    validates :location_id, presence: true
  
    def get_date
        self.date ? self.date : 'Add Date'
    end

    def get_cost
        self.cost ? '$' + self.cost.to_s : 'Add Cost'
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

    def logged_in?
        !!session[:name]
    end

    def current_user
        @traveler = (Traveler.find_by_id(params[:id]) || Traveler.new)
    end

    def require_logged_in
        return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
    end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

    def index
        @countries = Country.all
    end

    def new
    end

    def create
        @country = Country.create(country_params)
    end

    def delete
        Country.find_by_id(params[:id]).destroy
        redirect_to countries_path
    end

    private

    def country_params
        params.require(:country).permit(:name)
    end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

    def index
        @locations = Location.all
    end

    def new
        @location = Location.new
    end

    def create
        if Location.create(location_params)
            redirect_to locations_path
        else
            render :new
        end
    end

    def show
        @location = Location.find_by_id(params[:id])
    end

    def edit
        @location = Location.find_by_id(params[:id])
    end

    def update
        @location = Location.find_by_id(params[:id])
        @location.update(location_params)
        
        redirect_to locations_path
    end

    def destroy
        location = Location.find_by_id(params[:id])
        location.trips.each { |trip| trip.destroy }
        location.destroy
        
        redirect_to locations_path
    end

    private

    def location_params
        params.require(:location).permit(:city, :country_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    skip_before_action :verify_authenticity_token, only: :create

    def new
        @traveler = Traveler.new
    end

    def create
        @traveler = Traveler.find_by(traveler_params(:username))
        return head(:forbidden) unless @traveler.authenticate(params[:traveler][:password])
        
        session[:id] = @traveler.id
        session[:username] = @traveler.username
        
        redirect_to traveler_path(@traveler)
    end

    def destroy
        reset_session
        redirect_to root_path
    end

    private

    def traveler_params(*args)
        params.require(:traveler).permit(*args)
    end

end

app/controllers/travelers_controller.rb
class TravelersController < ApplicationController

    def new
        @traveler = Traveler.new
    end

    def create
        if auth
            @traveler = Traveler.find_or_create_by(username: auth['info']['nickname'])
            @traveler.password = auth['uid']
            @traveler.save

            session[:id] = @traveler.id
            session[:username] = @traveler.username

            redirect_to traveler_path(@traveler)
        else
            @traveler = Traveler.create(traveler_params)

            session[:id] = @traveler.id
            session[:username] = @traveler.username

            redirect_to traveler_path(@traveler)
        end
    end

    def show
        @traveler = Traveler.find_by_id(params[:id])
    end

    private

    def auth
        request.env['omniauth.auth']
    end

    def traveler_params
        params.require(:traveler).permit(:username, :password, :password_confirmation)
    end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

    before_action :get_traveler

    def index
        @trips = Trip.all.filter { |t| t.traveler_id == session[:id] }
    end
    
    def show
        @trip = @traveler.trips.find_by_id(params[:id])
    end

    def new
        @trip = Trip.new
    end

    def create
        Trip.create(trip_params(:traveler_id, :location_id))

        redirect_to trips_path
    end

    def edit
        @trip = Trip.find_by_id(params[:id])
    end

    def update
        @trip = Trip.find_by_id(params[:id])
        if date_formatted? &&
            @trip.update(trip_params(:date, :cost))

            redirect_to trips_path
        else
            # flash.alert = "Please make sure the date is formatted correctly."
            render :edit
        end  
    end

    def destroy
        trip = Trip.find_by_id(params[:id])
        trip.destroy
        
        redirect_to trips_path
    end

    private

    def date_formatted?
        params[:trip][:date].match('^\d\d/\d\d/\d\d\d\d$')
    end



    def get_traveler
        @traveler = Traveler.find_by_id(params[:id])
    end

    def trip_params(*args)
        params.require(:trip).permit(*args)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def home

    end

    def about
        
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/country_helper.rb
module CountryHelper
    def display_country(location)
        @location.country.nil? ? link_to("Add Country", edit_location_path(@location)) : link_to(@location.country_name, country_path(@location.country))
      end
    
      def country_select(location, path)
        if existing_and_nested?
          hidden_field_tag "location[country_id]", @location.country_id
        else
          select_tag "location[country_id]", options_from_collection_for_select(Country.all, :id, :name)
        end
      end
    
      def display_name(location, path)
        if existing_and_nested?
            @location.country.name
        end
      end

      private

      def existing_and_nested?
        @location.country && @path == "nested"
      end
end

app/views/countries/index.html.erb
<h3 class='display-6'><u>Countries</u></h3>
<p>The following are the current countries a part of our travel packages:</p>

<ol class="list-group list-group-numbered">
  <% @countries.order(:name).each do |country|%>
    <li class="list-group-item"><%= country.name %></li>
  <% end %>
</ol>
<br>
<%# <ol> %>
    <%# <% @countries.order(:name).each do |country|%>
        <%# <li><%= country.name %></li>
    <%# <% end %>
<%# </ol> %>

<p>More countries are coming soon!</p>

app/views/layouts/_navbar.html.erb
    <%# <nav style='display: inline-block'>
        <% if session[:username] %>
            <%# <%= link_to 'Locations', locations_path %>
            <%# <%= link_to 'Countries', countries_path %>
            <%# <%= link_to 'Trips', trips_path %>
            <%# <%= link_to 'Your Profile', traveler_path(session[:id]) %>
        <%# <% end %>
        <%# <%= link_to 'About', about_path %>
    <%# </nav> %>
    <%# <br> %>

<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme='dark' >
  <div class="container-fluid">
    <a class="navbar-brand fs-2" href="#">Trip Planner</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About', about_path, class: 'nav-link active' %>
        </li>
        <% if session[:username] %>
          <li class="nav-item">
            <%= link_to 'Locations', locations_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Countries', countries_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Trips', trips_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Your Profile', traveler_path(session[:id]), class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= form_tag (logout_path) do %>
              <input class='nav-link active' type='submit' value='Logout'>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Local Sign In', new_session_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Local Sign Up', new_traveler_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'GitHub Sign In', '/auth/github', method: :post, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'GitHub Sign Up','https://github.com/signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F&source=header-home', class: 'nav-link active' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= session[:trav_params] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trip Planner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>

  <body class='bg-dark'>
    <%# <h1>Trip Planner</h1> %>

    <%# <%= render 'travelers/logout' %> 
    <%= render 'layouts/navbar' %>

    <%= yield %>
    
  </body>
</html>

app/views/locations/_form.html.erb
<br>
<%= form_for @location do |f| %>
    <%= f.label :city %>
    <%= f.text_field :city %>
    <br>
    <%= f.label :country_name %>
    <%= display_name(@location, @path) %>
    <%= country_select(@location, @path) %>
    <br>
    <br>
    <%= f.submit %>
<% end %>

app/views/locations/edit.html.erb
<%= render 'form' %>

app/views/locations/index.html.erb
<p class='h5 text-white'>Click a location below to add it to your trips!</p>

<table class="table table-dark table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Locations</th>
      <th scope="col">Options</th>
    </tr>
  </thead>
  <tbody>
    <% @locations.each_with_index do |location, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= link_to "#{location.name}", trips_path(trip: {location_id: location.id, traveler_id: session[:id]}), method: :post, class: 'nav-link active' %></td>
      <td><%= link_to 'Edit', edit_location_path(location), class: 'btn btn-success' %> <%=link_to 'Remove', location_path(location), method: :delete, class: 'btn btn-danger' %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add a Location', new_location_path, class: 'btn btn-primary' %>

<%# <table style='border-collapse:separate;border-spacing:20px 10px;'>
    <tr>
        <th><h3><u>Locations</u></h3></th>
        <th><h3><u>Options</u></h3></th>
    </tr>
    <% @locations.each do |location| %>
        <%# <tr> %>
            <%# <td><%= link_to "#{location.name}", trips_path(trip: {location_id: location.id, traveler_id: session[:id]}), method: :post </td> %>
            <%# <td><%= link_to 'Edit', edit_location_path(location)  | <%=link_to 'Remove', location_path(location), method: :delete </td> %>
        <%# </tr> %>
    <%# <% end %>
<%# </table> %>
<%# <br> %>

app/views/locations/new.html.erb
<%= render 'form' %>

app/views/locations/show.html.erb
<p><%= @location.city %>, <%= @location.country %></p>

app/views/travelers/_logout.html.erb
<% if session[:username] %>
  <%= form_tag (logout_path) do %>
    <input type='submit' value='Logout'>
  <% end %>
  <br>
<% end %>

app/views/travelers/_signup.html.erb
<%= form_for(@traveler) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit "Create" %>
<% end %>

app/views/travelers/new.html.erb
<h3>Please Sign up or <%= link_to 'Sign in', new_session_path %></h3>
<%= render 'signup' %>

app/views/travelers/show.html.erb
<p class='display-6'>Hello, <%= session[:username] %>!</p>
<p class='h6'>You have taken <%= @traveler.trips_taken %> of <%= @traveler.trips.count %>.</p>
<p class='h6'>All of your trips are projected to cost <%= @traveler.trips_total %>.</p>

app/views/trips/_form.html.erb
<br>
<%= params[:location_id] %>

app/views/trips/edit.html.erb
<p>Please enter the date in MM/DD/YYY format.</p>
<%= form_for @trip do |f| %>
    <%= f.label :date %>
    <%= f.text_field :date %>
    <br>
    <%= f.label :cost %>
    <%= f.text_field :cost %>
    <br>
    <br>
    <%= f.submit %>
<% end %>

app/views/trips/index.html.erb
<h3>Trips</h3>
<p>Add a <u>date</u> and <u>cost</u> when you are ready to take your trip planning to the next level!</p>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Location</th>
      <th scope="col">Date</th>
      <th scope="col">Cost</th>
    </tr>
  </thead>
  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.location.name %></td>
        <td><%= link_to trip.get_date, edit_trip_path(trip), class: 'btn btn-primary' %></td>
        <td><%= link_to trip.get_cost, edit_trip_path(trip), class: 'btn btn-primary' %></td>
        <td><%=link_to 'Delete', trip_path(trip), method: :delete, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%# <table style='border-collapse:separate;border-spacing:20px 10px;'> %>
    <%# <tr> %>
        <%# <th>Location</th> %>
        <%# <th>Date</th> %>
        <%# <th>Cost</th> %>
    <%# </tr> %>
    <%# <% @trips.each do |trip|  %>
        <%# <tr> %>
            <%# <td><%= trip.location.name </td> %>
            <%# <td><%= link_to trip.get_date, edit_trip_path(trip) </td> %>
            <%# <td><%= link_to trip.get_cost, edit_trip_path(trip) </td> %>
            <%# <td><%=link_to 'Remove', trip_path(trip), method: :delete </td> %>
        <%# </tr> %>
    <%# <% end  %>

<%# </table> %>

app/views/welcome/about.html.erb
<h3 class='display-5 text-white'>About</h3>

<% if session[:username] %>
    <p class='h6 text-white'>Thanks for being a member, <%= session[:username] %>!</p>
    <p class='text-white'><%= Location.find_by_id(Traveler.find_by_id(session[:id]).trips.last.location_id).name %></p>
<% else %>
    <p class='h6 text-white'> Please login or signup<p>
<% end %>

<%= link_to 'Home', root_path, class: 'btn btn-primary' %>

app/views/welcome/home.html.erb
<p>Please sign in or sign up with one of the methods below: </p>
<p><%= link_to 'Sign in', new_session_path %> or <%= link_to 'Sign up', new_traveler_path %></p>
<p>Github: <%= link_to 'Sign in', '/auth/github', method: :post %> or <%= link_to 'Sign up','https://github.com/signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F&source=header-home' %></p>

<%= session[:trav_params] %>
<br>